title: Data Driven Analyst @ Vietmart | SQL | Excel | Python | Power BI # your name (or website title) here
logo: "/images/Self Pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data and process-driven analyst with nearly 3 years of experience. 
  Specializing in SQL Databases and Power BI. 
  2 years of experience and skills in database management. 
  Experienced in producing data visualizations and business intelligence needed for decision-making.  <br><br>
  <a href="https://www.linkedin.com/in/averyjsmith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
